
spring:
    application:
        name: website-backend
    data:
        mongodb:
          uri: mongodb://localhost:27017/website


    servlet:
        multipart:
          enabled: true
          file-size-threshold: 2MB
          max-file-size: 10MB
          max-request-size: 10MB


server:
    port: 8084
    error:
        include-binding-errors: always
        include-message: always

logging:
  level:
    com.netflix.discovery: 'DEBUG'
    org.springframework.cloud.netflix.eureka: 'DEBUG'


#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'

  timelimiter:
    instances:
      price-service:
        timeout-duration: 5s

  retry:
    instances:
      price-service:
        wait-duration: 5s
        max-attempts: '3'